### ISSUE TITLE
OpenBLAS and NUM_THREADS

### ISSUE THREAD

**Issue by jakirkham** [jakirkham/nanshe-build#7]
_From @dineshbvadhia on June 23, 2015 19:35_

OpenBLAS detects the number of cores at runtime but the actual number cores used are determined by NUM_THREADS. If NUM_THREADS is to set to a high number during compilation then there is a good chance that all cores will be used. Eg. if NUM_THREADS = 128 then most multi-core machines will be covered.  

Has OpenBLAS been compiled with a large NUM_THREADS?

_Copied from original issue: jakirkham/nanshe#250_

**Comment by jakirkham** [comment]
@dineshbvadhia, I have moved your issue over here as `nanshe` does not compile OpenBLAS. This repo contains information about building dependencies of `nanshe` including OpenBLAS, which is built using `conda`.

Here you can see how OpenBLAS has been compiled ( `openblas/build.sh` ). `NUM_THREADS` has been fixed at `1`. Letting it vary freely has adverse effects on some OSes like CentOS. Also, this can be very bad when sharing some compute resource with others where you shouldn't use the full amount of cores on the machine (else harm other running programs). As a consequence, I feel setting this explicitly to `1` does not constitute a problem.

However, this can be overridden easily by setting environment variables before loading OpenBLAS ( https://github.com/xianyi/OpenBLAS#set-the-number-of-threads-with-environment-variables ). For example, before importing `numpy`. I have tested this in the past with the `OPENBLAS_NUM_THREADS` environment variable and can verify that this will change the number of threads used even if it has been compiled with `NUM_THREADS` at `1`.

If you have more questions, feel free to open another issue (if unrelated) or tack them on here.

**Comment by dineshbvadhia** [comment]
@jakirkham This is a perfect place for my question. Xianyi did confirm recently that NUM_THREADS can be set to a large number though he didn't mention there were problems with any linux OS.

The problem is when an application is developed on a machine with a known configuration and then distributing the application to run on linux machines with unknown configurations including the number of cores. This means that NUM_THREADS=1 cannot be overridden.

**Comment by jakirkham** [comment]
Just to start off, you see how I have built it. You are welcome to change it to fit your needs.

> This means that NUM_THREADS=1 cannot be overridden.

Not true. As stated, this can be overridden no problem just set `OPENBLAS_NUM_THREADS` as an environment variable to what you want it to be.

> The problem is when an application is developed on a machine with a known configuration and then distributing the application to run on linux machines with unknown configurations including the number of cores.

There is always a way to figure out details about your architecture. It only becomes difficult if the variety is great. Possible solutions include writing a shim that can pick up the number of cores another way and pass it forward (e.g. in python one could use `multiprocessing.cpu_count()` other languages have other strategies). Once you get this value, you can set the environment variable.

> he didn't mention there were problems with any linux OS.

He may not be aware of it. I don't remember if I raised an issue about it, but I remember running into the problem in the release used here.

**Comment by jakirkham** [comment]
I am going to go ahead and close this as I have no plans to remove `NUM_THREADS=1` until I see that it works on CentOS.
